### PR TITLE
Replace C v4l2 API implementation with pure Go implementation

### PR DESCRIPTION
**Pull request by fabian-z**
This pull request provides a pure Go implementation interacting directly with the v4l2 kernel API. It gives the following benefits:

- over 60% reduction in memory usage (maximum resident set size)
- easier cross compilation
- better code readability

Notes:
- Only the needed constants and structs were ported from v4l2 includes. ```ioctl``` package is forked from [github.com/paypal/gatt/linux/gioctl](https://github.com/paypal/gatt/tree/master/linux/gioctl) and converted to use ```golang.org/x/sys/unix```.
- The speed increase originally claimed was due to erroneous measurement. In fact execution speed is identical for both implementations (which should be logically expected).
- Testing was done on kernel 4.5.3 (x86_64) so far

Looking forward to your feedback.

### CODE REVIEW

**Comment by fabian-z** [comment]
There is a mismatch in v4l2_buffer which causes a wrong buffersize. Still investigating.

**Comment by fabian-z** [comment]
Small remaining issue was fixed (reversed order of copy arguments). This branch should be functionally equivalent now.

**Comment by blackjack** [comment]
@fabian-z , thank you for pull request. I'll try test it on a live hardware and merge it today. 
I just wonder why memory consumption reduced? C implementation doesn't allocate any data on heap and as far as I understand, Cgo doesn't do it either. 
Any ideas? (just for curiosity)

**Comment by blackjack** [comment]
Also it's not entirely clear about how we should use ioctl.go.
It looks like originally it comes from https://github.com/luismesas/goPi, so we could import it with
```go
import "github.com/luismesas/goPi/ioctl" 
```
instead of supplying it alongside with a library

**Comment by fabian-z** [comment]
If I remember correctly, the Go runtime allocates a completely new heap for Cgo to ensure memory safety for the Go part of the application.

About the ioctl package, the source is [github.com/paypal/gatt/linux/gioctl](https://github.com/paypal/gatt/tree/master/linux/gioctl) (as given above). I copied the package for two reasons:

1. 

 The package itself is small compared to the repository it lives in, which would mean every application which uses this library would download a large bogus repository on ```go get```

2. 

 Docs at [pkg/syscall](https://golang.org/pkg/syscall/) state that "Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository", which is not the case for the original ioctl package (it still uses syscall directly, which basically only continues to exist because of the Go 1.x compatibility promise)

**Comment by fabian-z** [comment]
A nice explanation for Cgo overhead can be found here: https://www.cockroachlabs.com/blog/the-cost-and-complexity-of-cgo/
The blog post mentions a large memory overhead for C.GoBytes, which is used to copy the frame from the C heap to the Go heap. In my branch, the frame is not copied but directly used from mmaped memory - I suspect this is the main reason for the reduced memory usage.

**Comment by fabian-z** [comment]
Thanks for merging! :+1:

**Comment by blackjack** [comment]
Sorry, looks like it doesn't work on a physical hardware - perhaps some byte conversion occurs, because stdout_streamer.go produces invalid MJPEG stream.

**Comment by blackjack** [comment]
Everything works fine - camera opens, streaming starts, but output data is just wrong - VLC fails to recognise it. I've checked out previous state (with C implementation) and it worked fine.

**Comment by fabian-z** [comment]
Could you try to strace both the original code and my branch? The devices I own unfortunately only produce YUYV422. There could be an undetected issue in ```setImageFormat```, but the difference should be visible there.

**Comment by fabian-z** [comment]
I forgot to mention that if you post the output, e.g. on [clbin.com](https://clbin.com/) I'd be glad to debug the error with you.

**Comment by blackjack** [comment]
I'm not sure what you expect me to post to :) Webcam output?
And yes, it looks like setImageFormat works not as it was working before, at least function returns different value than was supplied. In my case I've chosen Motion-JPEG (code 1196444237, but the function returned 480)

**Comment by blackjack** [comment]
Since I don't want to have not-working master, I'll create separate branch for that and will continue debugging.

**Comment by fabian-z** [comment]
What I did for debugging was modify ```stdout_streamer.go``` to remove the user choices and use exactly one combination, and afterwards execute
```strace ./stdout_streamer_bin > /dev/null 2> strace_output```
Let it run for some time (30 seconds should be more than enough), cancel the execution and grab the output. 

To post on clbin.com run
```cat strace_output | curl -F 'clbin=<-' https://clbin.com```
The result is quite helpful as it may point out the difference in actually executed syscalls.

I see your point, a master working for a broader range of devices with Cgo is definitely preferable over a lacking pure Go implementation.

**Comment by blackjack** [comment]
Ok, I've found out the reason why it wasn't working. 
The answer is padding of fields in structure. 
This is a C structure: 
```c
struct v4l2_format {
	__u32	 type;
	union {
		struct v4l2_pix_format		pix;     /* V4L2_BUF_TYPE_VIDEO_CAPTURE */
		struct v4l2_pix_format_mplane	pix_mp;  /* V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE */
		struct v4l2_window		win;     /* V4L2_BUF_TYPE_VIDEO_OVERLAY */
		struct v4l2_vbi_format		vbi;     /* V4L2_BUF_TYPE_VBI_CAPTURE */
		struct v4l2_sliced_vbi_format	sliced;  /* V4L2_BUF_TYPE_SLICED_VBI_CAPTURE */
		struct v4l2_sdr_format		sdr;     /* V4L2_BUF_TYPE_SDR_CAPTURE */
		__u8	raw_data[200];                   /* user-defined */
	} fmt;
};
```
And this is it's hex dump:
```
Sizeof fmt: 208
00000000   01 00 00 00 00 00 00 00  ff ff ff ff d0 02 00 00  |................|
00000010   4d 4a 50 47 00 00 00 00  00 00 00 00 00 00 00 00  |MJPG............|
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

Now this is v4l2_format definition from v4l2.go:

```go
type v4l2_format struct {
	_type uint32
	union [204]uint8
}
```

Hexdump:
```
00000000  01 00 00 00 00 05 00 00  d0 02 00 00 4d 4a 50 47  |............MJPG|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

As you can see, in Go structure there's 4 bytes missing before starting of union field. 
 
If I change definition to this: 
```go
type v4l2_format struct {
	_type uint32
	_     [4]uint8 //padding
	union [200]uint8
}
```
it will work
I wonder why Go compiler doesn't insert padding there by itself

**Comment by blackjack** [comment]
Also manually inserting padding looks like super platform-dependent thing which basically takes away hope for easier cross-compilation on different platforms.

**Comment by fabian-z** [comment]
I was just debugging this issue myself as I saw the discrepancy you mentioned in ```setImageFormat``` myself after instrumenting the relevant parts with debug statements.
The discrepancy in byte placement is indeed interesting, as magic numbers were not needed for the rest of the implementation. I will look into this tommorow and also try cross compilation with your fix.

**Comment by blackjack** [comment]
I would also like to say that the reason you don't experience this issue is perhaps because there's a default image format in a driver (which on my camera is YUV 4:2:2), which is the format you said you expect for images from your device. 
I probably need help with that, because it looks like go compiler should insert that padding automatically, so I'll try to ask for it on some forum/irc.

**Comment by fabian-z** [comment]
Indeed that may well be the reasons that it worked for my device despite the padding issue.
If I take the C sizeof a modified v4l2_format struct (leaving out the leading uint32 field), it returns as 200 bytes. Calculating the memory used as 200*8+32 = 1632, we have 1632 mod 64 = 32 bits (or 4 bytes), so the Go compiler is indeed not aligning the struct to the word boundary.
I found a [related blog post](http://dave.cheney.net/2015/10/09/padding-is-hard) from Dave Cheney, where he states that 

> The Go spec says the address of a struct’s fields must be naturally aligned.

So this case may even be worth filing an issue with the Go devs. A workaround could be to use something like
```
var wordWidth int
unsafe.Sizeof(int)
```
to calculate if manual padding is required.

**Comment by blackjack** [comment]
So I investigated it a little bit more and I discovered that the reason Go compiler doesn't insert padding is because it doesn't have to.
In C definition inside of union there's a struct with pointer, thus all union has to be aligned to 8 bytes on 64bit architecture. But Go structure doesn't know anything about it: it just sees byte array and thinks that it has to be aligned to 1 byte. 
Considering this, IMO a good choice for that would be to still have some C code that cannot be normally translated (like setting format, mb. requesting buffers etc), but the actual work - getting frames - implement in Go.

**Comment by blackjack** [comment]
Also I've managed to force Go compiler to align union. Consider this code:
```go
package main

import (
	"fmt"
	"unsafe"
)

var __pointer unsafe.Pointer

type Union struct {
	union [200 - unsafe.Sizeof(__pointer)]byte
	p     unsafe.Pointer
}

type S struct {
	field1 uint32
	union  Union
}

func main() {
	var x S
	fmt.Printf("Align: %d, size: %d, pointer size: %d\n", unsafe.Alignof(x.union), unsafe.Sizeof(x), unsafe.Sizeof(__pointer))
}
```
Looks very ugly but It works well both on 32bit and 64bit platforms.

**Comment by fabian-z** [comment]
Nice hack!
Did you test this in the complete application case on 32bit or only the alignment?
Because I worked around the issue using build constraints in my fork (see latest commit) and fixed a compile time problem with 32bit (in my case ARM). It builds successfully and the format code issue is not present on both 64bit and 32bit.
But I ran into a failing ```mmapQueryBuffer``` call because of "inappropriate ioctl call for device" (which suggests something is wrong with the struct size). C sizeof original struct from videodev2.h gives 88 on 64bit but 68 on 32bit.

**Comment by fabian-z** [comment]
Regarding readability and idiomatic Go style, I tried to structure my branch taking the Go std library as an example. The part about an empty struct member of certain size in order to control memory layout is even part of the [https://golang.org/ref/spec#Struct_types](Go spec). Of course this is swapping readability for duplicated code segments.

**Comment by blackjack** [comment]
> On 32bit, the Go implementation has unsafe.Sizeof(*v4l2_buffer{}) = 72 instead of 68, where on 64bit it has the correct size of 88 (identical to C). So there is another mismatch of 4 bytes going on, though only on 32bit. Any insight into this?

Probably the same reason. Try to compare unsafe.Alignof(union) in go and alignof(v4l2_buffer.m)

**Comment by fabian-z** [comment]
```
unsafe.Alignof(v4l2_buffer{}.union)
//output: 1
```
```
struct v4l2_buffer f;
_Alignof(f.m);
//output 4
```

**Comment by fabian-z** [comment]
I implemented a padding similar to the other union (see https://github.com/fabian-z/webcam/commit/056348a0fda5ed1b2298228ad5edd04dedc67bf5), the error changed to "function not implemented". So the struct size size is fine now, but some other error is still uncatched.

**Comment by blackjack** [comment]
I appeared that v4l2_buffer memory layout was correct. The error was that buffer offset was not read (see 008c830212ab0c5c24db0a7f887b08477bc77832). After fixing that, everything started working fine (at least on my hardware).
Apart from problem with union alignment, I have still concerns regarding endianess: little endian is used everywhere, and I think that can also lead to problems on some platforms.

**Comment by blackjack** [comment]
Also, I hope that after fixing issues mentioned above, I'll create a new release, since people already start experiencing problems with C implementation (e.g. #5), and looks like go implementation works lot better.

**Comment by blackjack** [comment]
Ok, in a264fd4780a0fc71796cdce49993178a5da8fb26 I've put hack with union alignment inside and also added function to detect native byte order. Can you test **goimpl** branch to see if it works on your hardware? Thanks

**Comment by fabian-z** [comment]
Nice catch with the variable instead of the pointer in https://github.com/blackjack/webcam/commit/008c830212ab0c5c24db0a7f887b08477bc77832. Though I wonder why this was not caught by [binary.Read](https://golang.org/src/encoding/binary/binary.go?s=5630:5889#L206).
Checking for endianess makes it even more portable across platforms.
I suspect the remaining issues were fixed by your changes and will test them tomorrow on both 64bit and cross compiling to ARMv6/7 when I have access to my ARM 32bit environment again.

**Comment by fabian-z** [comment]
I think one issue will still be present:
```unix.Timeval{}``` takes an [32bit integer on 32bit platforms](https://github.com/fabian-z/webcam/commit/4b12ecd18c28e5c9cb98240b3e2b5916fdd2271e#diff-dfed2659b102d290c499251f3f6bf728R66) and [64bit integer on 64bit platform](https://github.com/fabian-z/webcam/commit/4b12ecd18c28e5c9cb98240b3e2b5916fdd2271e#diff-ab11abe1162d72f685d4689300274336R68). There is no way I could work around that without using build constraints, because the Go compiler won't let you assign the different type in any code path of the application (regardless of the fact that you are checking the architecture). Maybe it would be possible to use unsafe for that, but I could not yet look into that.
Another alternative is again to move the ```waitForFrame``` function into seperate architecture files.

**Comment by blackjack** [comment]
I guess we could use [syscall/Timeval](https://golang.org/pkg/syscall/#Timeval) for that

**Comment by fabian-z** [comment]
It will be the same issue.
[https://golang.org/src/syscall/ztypes_linux_amd64.go?s=397:444#L19](syscall/ztypes_linux_amd64.go)
[https://golang.org/src/syscall/ztypes_linux_386.go?s=395:444#L19](syscall/ztypes_linux_386.go).

**Comment by fabian-z** [comment]
It will be the same issue.
[syscall/ztypes_linux_amd64.go](https://golang.org/src/syscall/ztypes_linux_amd64.go?s=397:444#L19)
[syscall/ztypes_linux_386.go](https://golang.org/src/syscall/ztypes_linux_386.go?s=395:444#L19)

**Comment by blackjack** [comment]
So much of trouble just to do select syscall.

**Comment by fabian-z** [comment]
I wonder since the size of ```int``` is equal to architecture word width already, if we can just define

```
type Timeval struct {
Sec  int
Usec int
}
```

and pass a pointer to that. I will try if this works and is portable tomorrow.

**Comment by blackjack** [comment]
There's also https://godoc.org/golang.org/x/sys/unix#NsecToTimeval which should help us

**Comment by fabian-z** [comment]
Indeed, ```NsecToTimeval``` provides a nice int64 interface on both amd64 and 386 Go architecture. So the fix could be as simple as [this small patch](https://clbin.com/0J5vP).

**Comment by blackjack** [comment]
I would rather make user specify timeout in nanoseconds instead to avoid all kinds of conversion errors because of multiplying number by billion (sic!) (b819f7275eb94bb1a594ec3783a8ade2d5e56828)

**Comment by fabian-z** [comment]
I think this is of course the ideal solution, but I did not want to suggest a change breaking the external API of the library. The multiplicator in my patch could be of course specified as 1e9 - or even as 1000*1000*1000 commented with ms, us and ns - to make it more clear.

**Comment by blackjack** [comment]
I also don't like that, but I have a disclaimer that API still can change. But probably you're right and I should revert last commit.

**Comment by fabian-z** [comment]
I updated my patch so you can apply it with ```git apply``` if you want: https://clbin.com/tNSaU
Type conversion should be no issue here, since the target type is much larger (uint32 -> int64).

**Comment by blackjack** [comment]
Thanks, applied the patch. I'll wait then until tomorrow when you check in on ARM, and then create a new release. Looking forward to hear from you.

**Comment by fabian-z** [comment]
So, cross compiling of the goimpl works due to the applied patch. 64bit operation works flawlessly with my hardware. Unfortunately, the error in ```mmapQueryBuffer``` function continues to persist for 32bit. On 32bit/ARM I get a return error of "invalid ioctl for device". If I change the union in ```v4l2_buffer``` struct to a length 4 instead of 8 bytes, the error changes to "function not implemented", which is returned by unix.Syscall6. I suspect this will be the same error on all 32bit systems, but plan on testing in a virtual machine when I find time for it.

**Comment by fabian-z** [comment]
I just tested in a x86 32bit VM and as expected, the same issue is present there. I get ```invalid ioctl for device``` with the unmodified goimpl branch. With a [4]uint8 union in v4l2_buffer the errno from mmap syscall on x86 is "bad address".

When I add debug statement as
```
fmt.Println(buffer.length, offset)
```
just before ```unix.Syscall6``` (of course still in ```mmapQueryBuffer```), I get the same parameters on x86 32bit and 64bit:
```2621440 0```

For 64bit, subsequent query buffer memory allocations with different offsets can be seen:
```
2621440 2621440
2621440 5242880
2621440 7864320
2621440 10485760
2621440 13107200
2621440 15728640
2621440 18350080
2621440 20971520
2621440 23592960
2621440 26214400
```
For 32bit, the mmap syscall will fail with ```panic: Failed to map memory: bad address``` instead of returning a valid pointer.
This still needs further debugging, I will try to compare straces next.

**Comment by blackjack** [comment]
So does it fail on ioctl or on mmap?
Can you compare length and offset value in C version with Go version? 
https://github.com/blackjack/webcam/blob/master/webcam.c#L158
https://github.com/blackjack/webcam/blob/goimpl/v4l2.go#L311

**Comment by fabian-z** [comment]
Unfortunately, both is the case. It fails on ioctl because of wrong struct size (reason of ```wrong ioctl for device``` error). After reducing union byte array size in v4l2_buffer to 4, ioctl succeeds and the application fails on the specified mmap syscall.

strace shows the expected syscall on 64bit and no proper decode of syscall parameters (only mmap() with errno) on 32bit.
Comparing length and offset of both implementations on 64bit, I see no difference for both the first and subsequent allocations.
On 32bit, I can't compare because the current master only gives me timeouts in stdout_streamer.go example. It seems mmapQueryBuffer is not reached because my printf debug statement is not executed.

**Comment by fabian-z** [comment]
Okay, I switched my testing VM from VirtualBox to libvirt (using qemu/KVM) and usb passthrough and video capture is working fine now (both with ffmpeg and the C implementation).

The buf.length and buf.m.offset values for the C implementation on 32bit are the exact same values as on 64bit (both implementations, see above) for every allocation.

While testing our goimpl branch, I could again confirm the ioctl struct size issue (described above). After reducing union byte array size in v4l2_buffer to 4, execution again fails during mmap syscall.
Buffer length and offset values are again identical to all the other tests: ```2621440 0```.
So basically the parameters are the same, but the syscall somehow fails with the Go implementation.

I structured my testing results below in case my writeup wasn't clear enough:
---

Branch: master
Architecture: x86 64bit, 32bit
Issues: none
First mmapQueryBuffer invocation parameters: 2621440 0

Branch: goimpl
Architecture: x86 64bit
Issues: none
First mmapQueryBuffer invocation parameters: 2621440 0

Branch: goimpl
Architecture: x86 32bit
Issues: Ioctl error due to struct size (4 bytes too much for whatever reason), mmap syscall failing with errno "bad address"
First mmapQueryBuffer invocation parameters: 2621440 0

Branch: goimpl
Architecture: ARM 32bit
Issues: Ioctl error due to struct size (see above), mmap syscall failing with errno "function not implemented"
First mmapQueryBuffer invocation parameters: not checked

**Comment by fabian-z** [comment]
The mmap call seems to return EFAULT, for which the man page says

> http://linux.die.net/man/2/mmap2
> EFAULT
>  Problem with getting the data from user space

and strace (like Go) gives the error string as "bad address".

**Comment by cmatsuoka** [comment]
Confirmed "Fail to map memory: inappropriate ioctl for device" error on a 32-bit Raspberry Pi. (This was reported by an user, I don't have direct access to the hardware.)

**Comment by blackjack** [comment]
I don't have 32bit hardwarde ATM. I'll try to do play around with Virtualbox on this weekend and fix the issue

**Comment by fabian-z** [comment]
So far, I had no luck in identifying the root cause for the mmap issue - appreciate that you are looking into this. I would recommend using libvirt over VirtualBox, since I had no luck setting up my webcam with USB passthrough under VirtualBox (see above). I also suggest that you try your VM setup with ffmpeg first to confirm the webcam is indeed working as intended.

**Comment by blackjack** [comment]
Can you point me at a good article on how to setup libvirt? Thanks

**Comment by fabian-z** [comment]
It basically depends on your distribution.
For example, for Arch Linux, you would install the "libvirt", "qemu" and "virt-manager" packages. For NAT networking, add "ebtables" and "dnsmasq" - bridged networking needs "bridge-utils". Authentication is usually done with polkit, so you would need that too if you don't want to run virt-manager as root.

Afterwards, starting libvirtd as a system service is necessary (again distribution specific, with systemd you use "systemctl start libvirtd") and you should be able to start using the virt-manager application. Setup there is fairly straight forward using the provided GUI.

If I can assist you any further, please don't hesitate to let me know.

**Comment by cmatsuoka** [comment]
"Problem getting data from user space" is a rather strange error message for `sys_mmap2()`. It looks like it made more sense in the old mmap call that returned EFAULT when `copy_from_user()` failed (and EINVAL when the offset was not properly page-aligned), but the new one doesn't seem to do that. Maybe the error description is misleading and the real error is elsewhere?

**Comment by blackjack** [comment]
I've updated goimpl branch with updated implementation for both 32 and 64 bit arch.
I've resolved all previous errors for 32 bit, but there's still one left: incorrect data is received on some frames (vlc complains on broken mjpeg).

**Comment by fabian-z** [comment]
Nice that you could fix the remaining issues - although I have to admit I don't see the actual fix on first glance - do you recall if it was with the FD_SET structure you replaced, or with one of the syscalls?
I will test as soon as possible on my 32bit hardware and my virtual machine environment to verify.

**Comment by fabian-z** [comment]
I now tested the current goimpl branch in my 32bit/i686 virtual machine setup on a clean live image and was able to produce a valid raw yuyv422 stream with my device - I encoded with ffmpeg to h264 without error & viewed in vlc.

**Comment by blackjack** [comment]
@fabian-z  @cmatsuoka Thank you very much guys for help, sorry that I wasn't very active lately. I also tested the new implementation on several devices and it worked fine, so I'll make a new release then.

**Pull request merged**
