### PR TITLE
new http mjpeg streaming example

### PR DESCRIPTION
**Pull request by djadala**
Support 2 pixel formats - 'YUYV 4:2:2' & 'GSPCA PJPG ' , more formats can be added.
Use "image/jpeg" package to convert images to jpeg
Use cgo for converting PJPG to RGB.

Regards.

### CODE REVIEW

**Comment by blackjack** [comment]
Hi, @djadala , thanks for pr. Unfortunately I cannot merge it in current state due to 2 reasons:
- The library doesn't use cgo layer anymore due to several reasons (see #4  and #5), thus using go native types and functions is strongly preferable.
- Travis CI reports build issues

Looking forward to cooperation

**Comment by djadala** [comment]
Hi,
1.  cgo is used by new example, not library,
2. new example use libv4lconvert - `apt-get install libv4l-dev` on debian based distro

**Comment by blackjack** [comment]
1. Yes, I understand that, still I think we should avoid cgo even in examples.
2. Please resolve library issues by updating [.travis.yml](.travis.yml)

**Comment by meldron** [comment]
Works for me

**Comment by djadala** [comment]
HI, i modified example to work with current webcam package.
Regards

**Comment by djadala** [comment]
And doesn't, use cgo.

**Comment by ChaosCA** [comment]
Thank you @djadala

**Pull request merged**
